// Code generated by gen-data. DO NOT EDIT.

package gamedata

import (
	"github.com/go-pantheon/roma/gen/gamedata/base"
)

var (
	heroBaseDatas *HeroBaseDatas

	heroConstantData *HeroConstantData

	heroLevelDatas *HeroLevelDatas

	heroSkillDatas *HeroSkillDatas

	propertyAttributeData *PropertyAttributeData

	propertyFormulaDatas *PropertyFormulaDatas

	rechargeProductDatas *RechargeProductDatas

	resourceConstantData *ResourceConstantData

	resourceItemDatas *ResourceItemDatas

	resourceRadioDatas *ResourceRadioDatas

	resourcePackDatas *ResourcePackDatas
)

func loadGen(dir string) {
	var err error

	if err = base.Load(dir); err != nil {
		panic(err)
	}

	heroBaseDatas, err = newHeroBaseDatas(base.HeroBaseDataBaseGens)
	if err != nil {
		panic(err)
	}

	heroConstantData, err = newHeroConstantData(base.HeroConstantDataBaseGen)
	if err != nil {
		panic(err)
	}

	heroLevelDatas, err = newHeroLevelDatas(base.HeroLevelDataBaseGens)
	if err != nil {
		panic(err)
	}

	heroSkillDatas, err = newHeroSkillDatas(base.HeroSkillDataBaseGens)
	if err != nil {
		panic(err)
	}

	propertyAttributeData, err = newPropertyAttributeData(base.PropertyAttributeDataBaseGen)
	if err != nil {
		panic(err)
	}

	propertyFormulaDatas, err = newPropertyFormulaDatas(base.PropertyFormulaDataBaseGens)
	if err != nil {
		panic(err)
	}

	rechargeProductDatas, err = newRechargeProductDatas(base.RechargeProductDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourceConstantData, err = newResourceConstantData(base.ResourceConstantDataBaseGen)
	if err != nil {
		panic(err)
	}

	resourceItemDatas, err = newResourceItemDatas(base.ResourceItemDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourceRadioDatas, err = newResourceRadioDatas(base.ResourceRadioDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourcePackDatas, err = newResourcePackDatas(base.ResourcePackDataBaseGens)
	if err != nil {
		panic(err)
	}

	heroBaseDatas.build()

	heroConstantData.build()

	heroLevelDatas.build()

	heroSkillDatas.build()

	propertyAttributeData.build()

	propertyFormulaDatas.build()

	rechargeProductDatas.build()

	resourceConstantData.build()

	resourceItemDatas.build()

	resourceRadioDatas.build()

	resourcePackDatas.build()

	heroBaseDatas.init()

	heroConstantData.init()

	heroLevelDatas.init()

	heroSkillDatas.init()

	propertyAttributeData.init()

	propertyFormulaDatas.init()

	rechargeProductDatas.init()

	resourceConstantData.init()

	resourceItemDatas.init()

	resourceRadioDatas.init()

	resourcePackDatas.init()

}

func GetHeroBaseDataList() []*HeroBaseData {
	return heroBaseDatas.List
}

func GetHeroBaseData(key int64) *HeroBaseData {
	return heroBaseDatas.Map[key]
}

func GetHeroConstantData() *HeroConstantData {
	return heroConstantData
}

func GetHeroLevelDataList() []*HeroLevelData {
	return heroLevelDatas.List
}

func GetHeroLevelData(key int64) *HeroLevelData {
	return heroLevelDatas.Map[key]
}

func GetHeroSkillDataList() []*HeroSkillData {
	return heroSkillDatas.List
}

func GetHeroSkillData(key int64) *HeroSkillData {
	return heroSkillDatas.Map[key]
}

func GetPropertyAttributeData() *PropertyAttributeData {
	return propertyAttributeData
}

func GetPropertyFormulaDataList() []*PropertyFormulaData {
	return propertyFormulaDatas.List
}

func GetPropertyFormulaData(key int64) *PropertyFormulaData {
	return propertyFormulaDatas.Map[key]
}

func GetRechargeProductDataList() []*RechargeProductData {
	return rechargeProductDatas.List
}

func GetRechargeProductData(key int64) *RechargeProductData {
	return rechargeProductDatas.Map[key]
}

func GetResourceConstantData() *ResourceConstantData {
	return resourceConstantData
}

func GetResourceItemDataList() []*ResourceItemData {
	return resourceItemDatas.List
}

func GetResourceItemData(key int64) *ResourceItemData {
	return resourceItemDatas.Map[key]
}

func GetResourceRadioDataList() []*ResourceRadioData {
	return resourceRadioDatas.List
}

func GetResourceRadioData(key int64) *ResourceRadioData {
	return resourceRadioDatas.Map[key]
}

func GetResourcePackDataList() []*ResourcePackData {
	return resourcePackDatas.List
}

func GetResourcePackData(key int64) *ResourcePackData {
	return resourcePackDatas.Map[key]
}
