// Code generated by gen-data. DO NOT EDIT.

package gamedata

import (
	"github.com/vulcan-frame/vulcan-game/gen/gamedata/base"
)

var (

	propertyAttributeData *PropertyAttributeData

	propertyFormulaDatas *PropertyFormulaDatas

	resourceConstantData *ResourceConstantData

	resourceItemDatas *ResourceItemDatas

	resourceRadioDatas *ResourceRadioDatas

	resourcePackDatas *ResourcePackDatas
)

func loadGen(dir string) {
	var err error

	if err = base.Load(dir); err != nil {
		panic(err)
	}

	propertyAttributeData, err = newPropertyAttributeData(base.PropertyAttributeDataBaseGen)
	if err != nil {
		panic(err)
	}

	propertyFormulaDatas, err = newPropertyFormulaDatas(base.PropertyFormulaDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourceConstantData, err = newResourceConstantData(base.ResourceConstantDataBaseGen)
	if err != nil {
		panic(err)
	}

	resourceItemDatas, err = newResourceItemDatas(base.ResourceItemDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourceRadioDatas, err = newResourceRadioDatas(base.ResourceRadioDataBaseGens)
	if err != nil {
		panic(err)
	}

	resourcePackDatas, err = newResourcePackDatas(base.ResourcePackDataBaseGens)
	if err != nil {
		panic(err)
	}

	propertyAttributeData.build()

	propertyFormulaDatas.build()

	resourceConstantData.build()

	resourceItemDatas.build()

	resourceRadioDatas.build()

	resourcePackDatas.build()

	propertyAttributeData.init()

	propertyFormulaDatas.init()

	resourceConstantData.init()

	resourceItemDatas.init()

	resourceRadioDatas.init()

	resourcePackDatas.init()

}

func GetPropertyAttributeData() *PropertyAttributeData {
	return propertyAttributeData
}

func GetPropertyFormulaDataList() []*PropertyFormulaData {
	return propertyFormulaDatas.List
}

func GetPropertyFormulaData(key int64) *PropertyFormulaData {
	return propertyFormulaDatas.Map[key]
}

func GetResourceConstantData() *ResourceConstantData {
	return resourceConstantData
}

func GetResourceItemDataList() []*ResourceItemData {
	return resourceItemDatas.List
}

func GetResourceItemData(key int64) *ResourceItemData {
	return resourceItemDatas.Map[key]
}

func GetResourceRadioDataList() []*ResourceRadioData {
	return resourceRadioDatas.List
}

func GetResourceRadioData(key int64) *ResourceRadioData {
	return resourceRadioDatas.Map[key]
}

func GetResourcePackDataList() []*ResourcePackData {
	return resourcePackDatas.List
}

func GetResourcePackData(key int64) *ResourcePackData {
	return resourcePackDatas.Map[key]
}
