// Code generated by gen-datas. DO NOT EDIT.

package gamedata

import "github.com/vulcan-frame/vulcan-game/pkg/util/formula"

func (d *PropertyFormulaDataGen) CalcSteakCapacity(
	UserSteakCapacity float64,
) (float64, error) {
	return formula.Calc(d.Formula, map[string]float64{
		"UserSteakCapacity": UserSteakCapacity,
	})
}
