// Code generated by gen-datas. DO NOT EDIT.

package gamedata

import (
	property_base "github.com/go-pantheon/roma/gen/gamedata/base/property"
	"github.com/pkg/errors"
)

var _ = errors.New("import holding")

// PropertyAttributeDataGen excel/Property/Attribute.xlsx:Attribute
type PropertyAttributeDataGen struct {
	*property_base.AttributeDataBaseGen
}

func newPropertyAttributeData(base *property_base.AttributeDataBaseGen) (d *PropertyAttributeData, err error) {
	d = &PropertyAttributeData{}

	d.PropertyAttributeDataGen, err = newPropertyAttributeDataGen(base)
	if err != nil {
		return nil, err
	}
	return d, nil
}

func newPropertyAttributeDataGen(base *property_base.AttributeDataBaseGen) (d *PropertyAttributeDataGen, err error) {
	d = &PropertyAttributeDataGen{
		AttributeDataBaseGen: base,
	}

	return d, nil
}

func (d *PropertyAttributeDataGen) build() {

}

func (d *PropertyAttributeDataGen) init() error {
	return nil
}
