// Code generated by gen-datas. DO NOT EDIT.

package gamedata

import "github.com/vulcan-frame/vulcan-game/pkg/util/formula"

func (d *PropertyFormulaDataGen) CalcSteakCapacity(
	UserSteakCapacity float64,
) (float64, error) {
	return formula.Calc(d.Formula, map[string]float64{
		"UserSteakCapacity": UserSteakCapacity,
	})
}

func (d *PropertyFormulaDataGen) CalcHeroAtk(
	HeroLevelAtk float64,
	HeroLevel float64,
) (float64, error) {
	return formula.Calc(d.Formula, map[string]float64{
		"HeroLevelAtk": HeroLevelAtk,
		"HeroLevel":    HeroLevel,
	})
}

func (d *PropertyFormulaDataGen) CalcHeroHp(
	HeroLevelHp float64,
	HeroLevel float64,
) (float64, error) {
	return formula.Calc(d.Formula, map[string]float64{
		"HeroLevelHp": HeroLevelHp,
		"HeroLevel":   HeroLevel,
	})
}
