// Code generated by gen-datas. DO NOT EDIT.

package gamedata

import (
	resource_base "github.com/go-pantheon/roma/gen/gamedata/base/resource"
	"github.com/pkg/errors"
)

var _ = errors.New("import holding")

// ResourceConstantDataGen excel/Resource/item.xlsx:Constant
type ResourceConstantDataGen struct {
	*resource_base.ConstantDataBaseGen

	SteakIDData *ResourceItemData

	OnCreatedItemsItemPrizes *ItemPrizes
}

func newResourceConstantData(base *resource_base.ConstantDataBaseGen) (d *ResourceConstantData, err error) {
	d = &ResourceConstantData{}

	d.ResourceConstantDataGen, err = newResourceConstantDataGen(base)
	if err != nil {
		return nil, err
	}
	return d, nil
}

func newResourceConstantDataGen(base *resource_base.ConstantDataBaseGen) (d *ResourceConstantDataGen, err error) {
	d = &ResourceConstantDataGen{
		ConstantDataBaseGen: base,
	}

	return d, nil
}

func (d *ResourceConstantDataGen) build() {
	d.SteakIDData = GetResourceItemData(d.SteakID)

	if v, err := TryNewItemPrizes(d.OnCreatedItems); err != nil {
		panic(errors.WithMessagef(err, "File:%s Id=%d", d.Table(), d.Id()))
	} else {
		d.OnCreatedItemsItemPrizes = v
	}

}

func (d *ResourceConstantDataGen) init() error {
	return nil
}
