// Code generated by gen-datas. DO NOT EDIT.

package gamedata

import (
	resource_base "github.com/vulcan-frame/vulcan-game/gen/gamedata/base/resource"
	"github.com/pkg/errors"
)

var _ = errors.New("import holding")

// ResourceRadioDatas excel/Resource/item.xlsx:Radio
type ResourceRadioDatas struct {
	List []*ResourceRadioData
	Map  map[int64]*ResourceRadioData
}

// ResourceRadioDataGen excel/Resource/item.xlsx:Radio
type ResourceRadioDataGen struct {
	*resource_base.RadioDataBaseGen

	GroupWeightsGroupWeights *GroupWeights
	GroupItemsItemPrizesList []*ItemPrizes
}

func newResourceRadioDatas(bases *resource_base.RadioDataBaseGens) (*ResourceRadioDatas, error) {
	ds := &ResourceRadioDatas{
		List: make([]*ResourceRadioData, 0, len(bases.DataBases)),
		Map:  make(map[int64]*ResourceRadioData, len(bases.DataBases)),
	}
	for _, base := range bases.DataBases {
		d, err := newResourceRadioData(base)
		if err != nil {
			return nil, err
		}
		ds.List = append(ds.List, d)
		ds.Map[d.ID] = d
	}
	return ds, nil
}

func newResourceRadioData(base *resource_base.RadioDataBaseGen) (d *ResourceRadioData, err error) {
	d = &ResourceRadioData{}

	d.ResourceRadioDataGen, err = newResourceRadioDataGen(base)
	if err != nil {
		return nil, err
	}
	return d, nil
}

func newResourceRadioDataGen(base *resource_base.RadioDataBaseGen) (d *ResourceRadioDataGen, err error) {
	d = &ResourceRadioDataGen{
		RadioDataBaseGen: base,
	}

	return d, nil
}

func (ds *ResourceRadioDatas) init() error {
	for _, d := range ds.List {
		if err := d.init(); err != nil {
			return err
		}
	}
	return nil
}

func (ds *ResourceRadioDatas) build() {
	for _, d := range ds.List {
		d.build()
	}
}

func (d *ResourceRadioDataGen) build() {
	if v, err := TryNewGroupWeights(d.GroupWeights); err != nil {
		panic(errors.WithMessagef(err, "File:%s Id=%d", d.Table(), d.Id()))
	} else {
		d.GroupWeightsGroupWeights = v
	}

	if v, err := TryNewItemPrizesList(d.GroupItems); err != nil {
		panic(errors.WithMessagef(err, "File:%s Id=%d", d.Table(), d.Id()))
	} else {
		d.GroupItemsItemPrizesList = v
	}

}

func (d *ResourceRadioDataGen) init() error {
	return nil
}
