label:
  service: "${SERVICE:roma.player.service}"
  profile: "${PROFILE:DEV}"
  version: "${VERSION:v0.0.1}"
  color: "${COLOR:local}"
  node: "${NODE}"
  language: "${LANGUAGE:en}"
trace:
  endpoint: http://localhost:14268/api/traces
log:
  type: zap
  level: debug
server:
  http:
    addr: 0.0.0.0:8102
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9102
    timeout: 5s
data:
  postgresql:
    source: ${POSTGRES_SOURCE}
    database: ${POSTGRES_DATABASE}
    dial_timeout: ${POSTGRES_DIAL_TIMEOUT}
  redis:
    addr: ${REDIS_ADDR}
    password: ${REDIS_PASSWORD}
    dial_timeout: ${REDIS_DIAL_TIMEOUT}
    read_timeout: ${REDIS_READ_TIMEOUT}
    write_timeout: ${REDIS_WRITE_TIMEOUT}
recharge:
  apple:
    bundle_id: ${APPLE_RECHARGE_BUNDLE_ID}
  google:
    json: json
    pub_key: ${GOOGLE_RECHARGE_PUB_KEY}
    package_name: ${GOOGLE_RECHARGE_PACKAGE_NAME}
