// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Gate          *Gate                  `protobuf:"bytes,2,opt,name=gate,proto3" json:"gate,omitempty"`
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Log           *Log                   `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Bootstrap) GetGate() *Gate {
	if x != nil {
		return x.Gate
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Unencrypted   bool                   `protobuf:"varint,4,opt,name=unencrypted,proto3" json:"unencrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Label) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Label) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Label) GetUnencrypted() bool {
	if x != nil {
		return x.Unencrypted
	}
	return false
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Gate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []string               `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gate) Reset() {
	*x = Gate{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gate) ProtoMessage() {}

func (x *Gate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gate.ProtoReflect.Descriptor instead.
func (*Gate) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Gate) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

type App struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FirstUid          int64                  `protobuf:"varint,1,opt,name=first_uid,json=firstUid,proto3" json:"first_uid,omitempty"`
	ServerId          int64                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	WorkerCount       int64                  `protobuf:"varint,3,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	LoginInterval     *durationpb.Duration   `protobuf:"bytes,4,opt,name=login_interval,json=loginInterval,proto3" json:"login_interval,omitempty"`
	StatusAdmin       bool                   `protobuf:"varint,5,opt,name=status_admin,json=statusAdmin,proto3" json:"status_admin,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,6,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	WorkMinInterval   *durationpb.Duration   `protobuf:"bytes,7,opt,name=work_min_interval,json=workMinInterval,proto3" json:"work_min_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *App) GetFirstUid() int64 {
	if x != nil {
		return x.FirstUid
	}
	return 0
}

func (x *App) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *App) GetWorkerCount() int64 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *App) GetLoginInterval() *durationpb.Duration {
	if x != nil {
		return x.LoginInterval
	}
	return nil
}

func (x *App) GetStatusAdmin() bool {
	if x != nil {
		return x.StatusAdmin
	}
	return false
}

func (x *App) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *App) GetWorkMinInterval() *durationpb.Duration {
	if x != nil {
		return x.WorkMinInterval
	}
	return nil
}

type Secret struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountAesKey        string                 `protobuf:"bytes,1,opt,name=account_aes_key,json=accountAesKey,proto3" json:"account_aes_key,omitempty"`
	ClientCertVersion    int32                  `protobuf:"varint,2,opt,name=client_cert_version,json=clientCertVersion,proto3" json:"client_cert_version,omitempty"`
	ClientCertPrivateKey string                 `protobuf:"bytes,3,opt,name=client_cert_private_key,json=clientCertPrivateKey,proto3" json:"client_cert_private_key,omitempty"`
	ServerCertVersion    int32                  `protobuf:"varint,4,opt,name=server_cert_version,json=serverCertVersion,proto3" json:"server_cert_version,omitempty"`
	ServerCert           string                 `protobuf:"bytes,5,opt,name=server_cert,json=serverCert,proto3" json:"server_cert,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Secret) GetAccountAesKey() string {
	if x != nil {
		return x.AccountAesKey
	}
	return ""
}

func (x *Secret) GetClientCertVersion() int32 {
	if x != nil {
		return x.ClientCertVersion
	}
	return 0
}

func (x *Secret) GetClientCertPrivateKey() string {
	if x != nil {
		return x.ClientCertPrivateKey
	}
	return ""
}

func (x *Secret) GetServerCertVersion() int32 {
	if x != nil {
		return x.ServerCertVersion
	}
	return 0
}

func (x *Secret) GetServerCert() string {
	if x != nil {
		return x.ServerCert
	}
	return ""
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\rinternal.conf\x1a\x1egoogle/protobuf/duration.proto\"\xac\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x05label\x18\x01 \x01(\v2\x14.internal.conf.LabelR\x05label\x12'\n" +
	"\x04gate\x18\x02 \x01(\v2\x13.internal.conf.GateR\x04gate\x12$\n" +
	"\x03app\x18\x03 \x01(\v2\x12.internal.conf.AppR\x03app\x12$\n" +
	"\x03log\x18\x04 \x01(\v2\x12.internal.conf.LogR\x03log\"i\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12 \n" +
	"\vunencrypted\x18\x04 \x01(\bR\vunencrypted\"/\n" +
	"\x03Log\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x1a\n" +
	"\x04Gate\x12\x12\n" +
	"\x04addr\x18\x01 \x03(\tR\x04addr\"\xd8\x02\n" +
	"\x03App\x12\x1b\n" +
	"\tfirst_uid\x18\x01 \x01(\x03R\bfirstUid\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x03R\bserverId\x12!\n" +
	"\fworker_count\x18\x03 \x01(\x03R\vworkerCount\x12@\n" +
	"\x0elogin_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rloginInterval\x12!\n" +
	"\fstatus_admin\x18\x05 \x01(\bR\vstatusAdmin\x12H\n" +
	"\x12heartbeat_interval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12E\n" +
	"\x11work_min_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0fworkMinInterval\"\xe8\x01\n" +
	"\x06Secret\x12&\n" +
	"\x0faccount_aes_key\x18\x01 \x01(\tR\raccountAesKey\x12.\n" +
	"\x13client_cert_version\x18\x02 \x01(\x05R\x11clientCertVersion\x125\n" +
	"\x17client_cert_private_key\x18\x03 \x01(\tR\x14clientCertPrivateKey\x12.\n" +
	"\x13server_cert_version\x18\x04 \x01(\x05R\x11serverCertVersion\x12\x1f\n" +
	"\vserver_cert\x18\x05 \x01(\tR\n" +
	"serverCertB\x1cZ\x1amercury/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: internal.conf.Bootstrap
	(*Label)(nil),               // 1: internal.conf.Label
	(*Log)(nil),                 // 2: internal.conf.Log
	(*Gate)(nil),                // 3: internal.conf.Gate
	(*App)(nil),                 // 4: internal.conf.App
	(*Secret)(nil),              // 5: internal.conf.Secret
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: internal.conf.Bootstrap.label:type_name -> internal.conf.Label
	3, // 1: internal.conf.Bootstrap.gate:type_name -> internal.conf.Gate
	4, // 2: internal.conf.Bootstrap.app:type_name -> internal.conf.App
	2, // 3: internal.conf.Bootstrap.log:type_name -> internal.conf.Log
	6, // 4: internal.conf.App.login_interval:type_name -> google.protobuf.Duration
	6, // 5: internal.conf.App.heartbeat_interval:type_name -> google.protobuf.Duration
	6, // 6: internal.conf.App.work_min_interval:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
