account_aes_key: ihSj8Xd0CAxJoOTpdiEvts8EQNNHov3M
client_cert_version: 1
client_cert_private_key: |
  -----BEGIN PRIVATE KEY-----
  MC4CAQAwBQYDK2VwBCIEIDGE2hVaE1VTyB+cqSviouww9/A6CRKyXbIRxoRVaEqK
  -----END PRIVATE KEY-----

client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIB0DCCAYKgAwIBAgIBATAFBgMrZXAwdjELMAkGA1UEBhMCU0cxEjAQBgNVBAgT
  CVNpbmdhcG9yZTESMBAGA1UEBxMJU2luZ2Fwb3JlMR8wDAYDVQQKEwVKYW51czAP
  BgNVBAoTCFBhbnRoZW9uMR4wHAYDVQQDExVqYW51cy5nby1wYW50aGVvbi5kZXYw
  HhcNMjUwNjI3MTUwNjU5WhcNMjYwNjI3MTUwNjU5WjB2MQswCQYDVQQGEwJTRzES
  MBAGA1UECBMJU2luZ2Fwb3JlMRIwEAYDVQQHEwlTaW5nYXBvcmUxHzAMBgNVBAoT
  BUphbnVzMA8GA1UEChMIUGFudGhlb24xHjAcBgNVBAMTFWphbnVzLmdvLXBhbnRo
  ZW9uLmRldjAqMAUGAytlcAMhAFV5tkviR1rRgBKbkEnu7+rizFUxPTgUgB4Oq/XF
  Dyn6ozUwMzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
  VR0TAQH/BAIwADAFBgMrZXADQQCv6wrZwhVaZtL9CWHbwlbRmYiuTpwUP/wKpJDh
  ZLJk0sqKLLhPUXQpvw+5hQwAJlfUoz3eg+KlbGfZlgVArYgJ
  -----END CERTIFICATE-----

server_cert_version: 1
server_cert: |
  -----BEGIN CERTIFICATE-----
  MIIB0DCCAYKgAwIBAgIBATAFBgMrZXAwdjELMAkGA1UEBhMCU0cxEjAQBgNVBAgT
  CVNpbmdhcG9yZTESMBAGA1UEBxMJU2luZ2Fwb3JlMR8wDAYDVQQKEwVKYW51czAP
  BgNVBAoTCFBhbnRoZW9uMR4wHAYDVQQDExVqYW51cy5nby1wYW50aGVvbi5kZXYw
  HhcNMjUwNjI3MTUwNjA3WhcNMjYwNjI3MTUwNjA3WjB2MQswCQYDVQQGEwJTRzES
  MBAGA1UECBMJU2luZ2Fwb3JlMRIwEAYDVQQHEwlTaW5nYXBvcmUxHzAMBgNVBAoT
  BUphbnVzMA8GA1UEChMIUGFudGhlb24xHjAcBgNVBAMTFWphbnVzLmdvLXBhbnRo
  ZW9uLmRldjAqMAUGAytlcAMhAF7kbCX1keBpSEd5PIPD1UsnRaxgTdGODAlZv36L
  sCzSozUwMzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
  VR0TAQH/BAIwADAFBgMrZXADQQDlbDGoDqH/+ktjt4JsylInlof+DrmEG30VxGGx
  G904Ye6uVQxazt00y/Zz4JrV5+yv8Jnn5glqBePcG3P+VyAB
  -----END CERTIFICATE-----
